
import { store } from '../../store.js';
import { modalWindowCloseXHtml, modalNavBackHtml } from '../../utils/dock-sheet-chrome.js';

class ArboritoModalCertificateView extends HTMLElement {
    connectedCallback() {
        this.render();
    }

    close() {
        store.dismissModal();
    }

    render() {
        const ui = store.ui;
        const moduleId = store.value.modal.moduleId;

        // Retrieve version hash from bookmark if available to verify content state
        const node = store.findNode(moduleId);
        const bookmark = node ? store.getBookmark(node.id, node.content) : null;
        const versionId = bookmark ? bookmark.hash.substring(0, 8).toUpperCase() : 'LEGACY';

        // --- DYNAMIC AUTHORITY NAME LOGIC ---
        // Reads from the 'universeName' property in data.json which is set by the builder
        // based on content/meta.json.
        
        const rawData = store.value.rawGraphData || {};
        const activeSource = store.value.activeSource || {};
        
        let authorityName = ui.certSign; // Default Fallback
        
        // 1. Prioritize Internal Data Name (Set by Builder via content/meta.json)
        if (rawData.universeName && rawData.universeName !== "Arborito Library") {
            authorityName = rawData.universeName;
        } 
        // 2. Fallback to Source Name (Set in Source Manager)
        else if (activeSource.name) {
            authorityName = activeSource.name;
        }

        const content = `
        <div class="arborito-cert-view px-4 py-6 sm:px-8 sm:py-10 md:p-12 text-center bg-yellow-50 dark:bg-yellow-950/20 min-h-0 flex flex-col items-center justify-center relative overflow-x-hidden overflow-y-auto">
             <div class="arborito-cert-view__frame absolute inset-0 border-[6px] sm:border-[10px] md:border-[12px] border-double border-yellow-200 dark:border-yellow-900/40 m-3 sm:m-5 md:m-6 rounded-2xl sm:rounded-3xl pointer-events-none"></div>
             
             <!-- Watermark / Background Logo -->
             <div class="arborito-cert-view__watermark absolute text-[10rem] sm:text-[14rem] md:text-[18rem] pointer-events-none select-none text-slate-400 rotate-12">🎓</div>

             <div class="w-20 h-20 sm:w-24 sm:h-24 md:w-28 md:h-28 bg-white dark:bg-slate-900 rounded-full flex items-center justify-center text-4xl sm:text-5xl md:text-6xl arborito-cert-view__medallion border-4 border-yellow-400 mb-6 sm:mb-8 relative z-10">
                ${(node && node.icon) || '🎓'}
             </div>
             
             <h2 class="font-black text-xl sm:text-2xl md:text-4xl text-slate-800 dark:text-white mb-2 uppercase tracking-[0.15em] sm:tracking-[0.2em] relative z-10 px-1">${ui.certTitle}</h2>
             <div class="w-24 sm:w-32 h-1.5 bg-yellow-400 mb-6 sm:mb-8 relative z-10 rounded-full arborito-cert-view__accent"></div>
             
             <p class="text-slate-600 dark:text-slate-300 mb-3 sm:mb-4 italic text-base sm:text-lg md:text-xl relative z-10 px-2 max-w-xl mx-auto">${ui.certBody}</p>
             
             <h3 class="font-bold text-2xl sm:text-3xl md:text-5xl text-purple-600 dark:text-purple-400 mb-8 sm:mb-12 relative z-10 max-w-full sm:max-w-2xl leading-tight px-2 break-words">
                ${(node && node.name) || moduleId}
             </h3>
             
             <div class="flex flex-col sm:flex-row gap-8 sm:gap-12 md:gap-32 text-center text-xs sm:text-sm text-slate-400 font-mono relative z-10 uppercase tracking-widest w-full max-w-full px-1 sm:px-2">
                <div class="min-w-0 flex-1">
                    <div class="border-b-2 border-slate-300 dark:border-slate-700 pb-2 mb-2 w-full max-w-xs mx-auto text-slate-700 dark:text-slate-300 font-bold text-base sm:text-lg break-words">
                        ${new Date().toLocaleDateString()}
                    </div>
                    ${ui.certDate}
                </div>
                <div class="min-w-0 flex-1">
                    <div class="border-b-2 border-slate-300 dark:border-slate-700 pb-2 mb-2 w-full max-w-md mx-auto font-black text-slate-800 dark:text-white text-base sm:text-lg break-words whitespace-normal">
                        ${authorityName}
                    </div>
                    ${ui.certSign}
                </div>
             </div>
             
             <div class="mt-6 sm:mt-auto mb-3 sm:mb-4 flex flex-col gap-1 items-center opacity-70 hover:opacity-100 transition-opacity relative z-10">
                 <div class="text-[10px] text-slate-500 dark:text-slate-400 font-mono uppercase tracking-widest px-2 text-center">
                     VERIFICATION ID: ${versionId}
                 </div>
                 <div class="text-[9px] text-slate-500 dark:text-slate-500 text-center">
                     Generated by Arborito
                 </div>
             </div>
             
             <button id="btn-print" type="button" class="relative z-20 mt-2 sm:mt-4 md:absolute md:bottom-6 md:right-6 lg:bottom-8 lg:right-8 px-5 py-2.5 sm:px-6 sm:py-3 bg-slate-900 dark:bg-slate-800 text-white rounded-xl font-bold text-xs sm:text-sm uppercase tracking-wider hover:scale-105 transition-transform arborito-cert-view__print flex items-center gap-2 print:hidden mx-auto shrink-0">
                <span>🖨️</span> ${ui.printCert}
             </button>
        </div>`;

        // Increased to max-w-4xl for Landscape format
        this.innerHTML = `
        <div id="modal-backdrop" class="arborito-modal-backdrop--certificate fixed inset-0 z-[70] flex items-center justify-center bg-slate-950 p-4 md:p-4 animate-in fade-in arborito-modal-root">
            <div class="arborito-float-modal-card arborito-float-modal-card--certificate bg-white dark:bg-slate-900 rounded-[2rem] shadow-2xl relative overflow-hidden flex flex-col border border-slate-200 dark:border-slate-800 cursor-auto transition-all duration-300">
                <div class="arborito-float-modal-head arborito-dock-modal-hero shrink-0 px-4 pt-4 pb-2 print:hidden">
                    ${modalNavBackHtml(ui, 'arborito-mmenu-back shrink-0', { tagClass: 'btn-close' })}
                    <h2 class="arborito-mmenu-subtitle m-0 flex-1 min-w-0">${ui.certTitle}</h2>
                    ${modalWindowCloseXHtml(ui, 'btn-close')}
                </div>
                <div class="flex-1 min-h-0 overflow-y-auto overflow-x-hidden">${content}</div>
            </div>
        </div>`;

        this.querySelectorAll('.btn-close').forEach((b) => (b.onclick = () => this.close()));
        this.querySelector('#btn-print').onclick = () => window.print();
    }
}
customElements.define('arborito-modal-certificate-view', ArboritoModalCertificateView);
