/**
 * window.arborito public API surface.
 * Injected into cartridge iframes — keep in sync with host modules when noted.
 */
import { iframeSdkBlock } from './fragment.js';

export const GAME_SDK_API_FRAGMENT = iframeSdkBlock([
    '',
    '    window.arborito = {',
    '        user: user,',
    '        /** Error code strings (for games that branch on failure kind). Same as CODES values. */',
    '        ERROR_CODES: CODES,',
    '        /** AI Mode: \'static\' (no AI) or \'dynamic\' (AI available). Games should check this before using ask.* */',
    '        getAIMode: function() { return aiMode; },',
    '        lesson: {',
    '            next: function() { return bridge.getNextLesson(); },',
    '            list: function() { return bridge.getCurriculum(); },',
    '            at: function(idx) { return bridge.getLessonAt(idx); },',
    '            /* Returns { tags } parsed from the lesson @info block.',
    '               Spaced-repetition is decided by Arborito\'s SRS engine',
    '               (see arborito.memory.due / getStatus). */',
    '            readMeta: readLessonMeta',
    '        },',
    '        meta: {',
    '            read: readLessonMeta',
    '        },',
    '        /** Challenge Schema utilities for static mode games */',
    '        challenge: {',
    '            /** Check if a challenge object has all required fields */',
    '            isComplete: isChallengeComplete,',
    '            /** Get completeness score (0-5) and status */',
    '            getCompleteness: getChallengeCompleteness,',
            '            /** All lesson questionnaires on a lesson (challenge + challenges[]) */',
    '            fromLesson: getChallengesFromLesson,',
    '            /** Default empty challenge template */',
    '            template: function() {',
    '                return { core_concept: \'\', short_definition: \'\', main_question: \'\', correct_answer: \'\', traps: [], cloze_indices: [], steps: [], modes: [] };',
    '            },',
    '            /** Build duel/battle cards from lesson questionnaire (static-first). */',
    '            buildDuelDeck: function(lesson) {',
    '                return buildDuelDeckFromChallenge(lesson);',
    '            },',
    '            /**',
            '             * Lesson quiz modalities (multiple / recall / cloze / chips / steps).',
    '             * Mirrors arborito/src/features/learning/api/quiz-schema.js so cartridges and',
    '             * Python SDK games can render the full Care/Study experience.',
    '             */',
    '            modes: {',
    '                ALL: ALL_QUIZ_MODES.slice(),',
    '                MULTIPLE: QUIZ_MODE_MULTIPLE,',
    '                RECALL: QUIZ_MODE_RECALL,',
    '                CLOZE: QUIZ_MODE_CLOZE,',
    '                CHIPS: QUIZ_MODE_CHIPS,',
    '                STEPS: QUIZ_MODE_STEPS,',
    '                isPlayable: function(challenge, mode) {',
    '                    return modeIsPlayable(modesNormalizeChallenge(challenge), mode);',
    '                },',
    '                playable: function(challenge) { return getPlayableModesImpl(challenge); },',
    '                pick: function(challenge, blockId, salt) { return pickStudyQuizModeImpl(challenge, blockId, salt); },',
    '                buildCard: function(challenge, mode, opts) { return buildModeCardImpl(challenge, mode, opts); },',
    '                buildStudyCard: function(challenge, blockId, opts) { return buildStudyCardImpl(challenge, blockId, opts); },',
    '                /** Translated mode label, e.g. label(\'cloze\',\'ES\') -> \'Hueco\'. */',
    '                label: modeLabel,',
    '                /** CSS class fragment for styling per modality, e.g. " is-mode-cloze". */',
    '                className: modeClassName,',
    '                /** True when the player has to drag chips / steps into order (chips & steps modes). */',
    '                isOrdering: modeIsOrdering,',
    '                /** Compare what the player picked against the card\'s expected order. */',
    '                checkOrder: modeCheckOrder,',
    '                /** HTML for the answer area (chips for ordering, buttons for multiple-choice).',
    '                 *  opts: { showOpts, optsDisabled, lang }. */',
    '                renderAnswers: modeRenderAnswers',
    '            }',
    '        },',
    '        ask: {',
    '            json: function() {',
    '                if (aiMode === \'static\') {',
    '                    throw makeError(CODES.SAGE, \'AI not available in static mode. Switch to Dynamic AI mode to use ask.json.\');',
    '                }',
    '                return askJSONImpl.apply(null, arguments);',
    '            },',
    '            chat: function(messages, ctx) {',
    '                if (aiMode === \'static\') {',
    '                    throw makeError(CODES.SAGE, \'AI not available in static mode. Switch to Dynamic AI mode to use ask.chat.\');',
    '                }',
    '                return bridge.aiChat(messages, ctx);',
    '            }',
    '        },',
    '        xp: function(n) { bridge.addXP(n); },',
    '        exit: function() { bridge.close(); },',
    '        save: function(k, v) { return bridge.save(k, v); },',
    '        load: function(k) { return bridge.load(k); },',
    '        memory: {',
    '            due: function() { return bridge.getDue(); },',
    '            getStatus: function(nodeId) {',
    '                return typeof bridge.getMemoryStatus === \'function\' ? bridge.getMemoryStatus(nodeId) : null;',
    '            },',
    '            isDue: function(nodeId) {',
    '                return typeof bridge.isMemoryDue === \'function\' ? bridge.isMemoryDue(nodeId) : false;',
    '            },',
    '            report: function(nodeId, quality) { return bridge.reportMemory(nodeId, quality); }',
    '        },',
    '        /** Platform helpers every cartridge gets for free.',
    '         *  Mobile-friendly tap, screen-size probing, and HTML-safe escaping. */',
    '        platform: {',
    '            /** Tap that doesn\'t fire twice on mobile. Returns a cleanup function. */',
    '            onTap: onTap,',
    '            /** { width, height } of the usable area (accounts for mobile chrome). */',
    '            getScreenSize: getScreenSize,',
    '            /** Subscribe to resize / orientation. Returns a cleanup function. */',
    '            onScreenChange: onScreenChange,',
    '            /** Escape text for safe HTML insertion. */',
    '            escapeHtml: escText,',
    '            /** Escape values for safe attributes. */',
    '            escapeAttr: escAttr',
    '        },',
    '        quiz: async function(lesson, opts) {',
    '            opts = opts || {};',
    '            var count = opts.count != null ? opts.count : 3;',
    '            var staticQuiz = staticQuizFromLesson(lesson, count);',
    '            if (aiMode === \'static\') {',
    '                if (!staticQuiz || !staticQuiz.length) {',
    '                    throw makeError(CODES.SAGE, \'Complete the lesson questionnaire to play in static mode.\');',
    '                }',
    '                return staticQuiz;',
    '            }',
            '            /* Dynamic: reuse author questionnaire when possible; AI fills remaining slots. */',
    '            if (staticQuiz && staticQuiz.length >= count) {',
    '                return shuffleArray(staticQuiz).slice(0, count);',
    '            }',
    '            var have = staticQuiz ? staticQuiz.length : 0;',
    '            var need = Math.max(1, count - have);',
    '            var langName = (user.lang === \'ES\') ? \'Spanish\' : \'English\';',
    '            var contextBlock = lessonContextBlockForAi(lesson);',
    '            var prompt =',
    '                contextBlock + \'\\\\n\\\\n\' +',
    '                \'The user language is \' + langName + \'.\\\\n\' +',
    '                \'Generate \' + need + \' additional quiz items grounded in the context above. Prefer facts from the author questionnaires when present.\\\\n\' +',
    '                \'For each item: short topic name, question, CORRECT answer (max 4 words), PLAUSIBLE wrong answer (max 4 words).\\\\n\' +',
    '                \'ALL output MUST be in \' + langName + \'.\\\\n\' +',
    '                \'Return ONLY a valid JSON array:\\\\n\' +',
    '                \'[\\\\n    { "topic": "Short Topic Name", "q": "Question text", "correct": "Correct Answer", "wrong": "Wrong Answer" }\\\\n]\';',
    '            var aiItems = await askJSONImpl(prompt, null, opts.askOptions);',
    '            var merged = (staticQuiz || []).concat(Array.isArray(aiItems) ? aiItems : []);',
    '            if (!merged.length) {',
    '                throw makeError(CODES.EMPTY, \'AI_EMPTY_RESPONSE: Could not build quiz from lesson.\');',
    '            }',
    '            return merged.slice(0, count);',
    '        },',
    '        matchPairs: async function(lesson, opts) {',
    '            opts = opts || {};',
    '            var n = opts.count != null ? opts.count : 6;',
    '            var fillFromCurriculum = opts.fillFromCurriculum !== false;',
    '            var staticPairs = await staticMatchPairsWithCurriculumFill(lesson, n, fillFromCurriculum);',
    '            if (aiMode === \'static\') {',
    '                if (!staticPairs || staticPairs.length < 1) {',
    '                    throw makeError(CODES.SAGE, \'Complete the lesson questionnaire to play in static mode.\');',
    '                }',
    '                return staticPairs;',
    '            }',
            '            /* Dynamic: author questionnaire pairs first; AI fills remaining slots. */',
    '            if (staticPairs.length >= n) {',
    '                return staticPairs.slice(0, n);',
    '            }',
    '            var need = Math.max(1, n - staticPairs.length);',
    '            var langName = (user.lang === \'ES\') ? \'Spanish\' : \'English\';',
    '            var contextBlock = lessonContextBlockForAi(lesson);',
    '            var prompt =',
    '                contextBlock + \'\\\\n\\\\n\' +',
    '                \'Task: Create content for a Memory-style card matching game in \' + langName + \'.\\\\n\' +',
    '                \'Generate \' + need + \' NEW pairs (term + definition) grounded in the context. Prefer author questionnaire facts.\\\\n\' +',
    '                \'Rules: Terms 1-3 words; definitions max 8 words; all in \' + langName + \'; pairs unique.\\\\n\' +',
    '                \'Do NOT duplicate these existing pairs: \' + JSON.stringify(staticPairs) + \'\\\\n\' +',
    '                \'Output: ONLY a valid JSON array: [{"t": "Term", "d": "Definition"}, ...]\';',
    '            var aiPairs = await askJSONImpl(prompt, null, opts.askOptions);',
    '            var merged = sanitizeMemoryPairs(',
    '                (staticPairs || []).concat(Array.isArray(aiPairs) ? aiPairs : []),',
    '                n',
    '            );',
    '            if (fillFromCurriculum && merged.length < n && lesson) {',
    '                var curriculum = bridge.getCurriculum ? bridge.getCurriculum() : [];',
    '                var startIdx = -1;',
    '                for (var fi = 0; fi < curriculum.length; fi++) {',
    '                    if (curriculum[fi] && curriculum[fi].id === lesson.id) {',
    '                        startIdx = fi;',
    '                        break;',
    '                    }',
    '                }',
    '                if (startIdx >= 0 && typeof bridge.getLessonAt === \'function\') {',
    '                    for (var fj = startIdx + 1; fj < curriculum.length && merged.length < n; fj++) {',
    '                        var followL = await bridge.getLessonAt(fj);',
    '                        if (!followL || !lessonHasMemoryContent(followL)) continue;',
    '                        merged = sanitizeMemoryPairs(',
    '                            merged.concat(staticMatchPairsFromLessons([followL], n)),',
    '                            n',
    '                        );',
    '                    }',
    '                }',
    '            }',
    '            if (!merged.length) {',
    '                throw makeError(CODES.EMPTY, \'AI_EMPTY_RESPONSE: Could not build memory pairs from lesson.\');',
    '            }',
    '            return merged;',
    '        }',
    '    };',
]);
