/**
 * window.arborito public API surface.
 * Injected into cartridge iframes, keep in sync with host modules when noted.
 */
import { iframeSdkBlock } from './fragment.js';

export const GAME_SDK_API_FRAGMENT = iframeSdkBlock([
    '',
    '    window.arborito = {',
    '        user: user,',
    '        /** Error code strings (for games that branch on failure kind). Same as CODES values. */',
    '        ERROR_CODES: CODES,',
    '        /** AI Mode: \'static\' (no AI) or \'dynamic\' (AI available). Games should check this before using ask.* */',
    '        getAIMode: function() { return aiMode; },',
    '        lesson: {',
    '            next: function() { return bridge.getNextLesson(); },',
    '            list: function() { return bridge.getCurriculum(); },',
    '            at: function(idx) { return bridge.getLessonAt(idx); },',
    ' /** Prose only : strips @section, @quiz, markdown, etc. */',
    '            plainText: function(lessonOrRaw) {',
    '                if (bridge.getLessonPlainText) return bridge.getLessonPlainText(lessonOrRaw);',
    '                if (lessonOrRaw && typeof lessonOrRaw === \'object\') return String(lessonOrRaw.text || \'\').trim();',
    '                return String(lessonOrRaw || \'\').trim();',
    '            },',
    '            /** Resolve a playlist lesson by node id (for quiz.pool items with lessonId). */',
    '            byId: lessonById,',
    '            /* Returns { tags } parsed from the lesson @info block.',
    '               Spaced-repetition is decided by Arborito\'s SRS engine',
    '               (see arborito.memory.due / getStatus). */',
    '            readMeta: readLessonMeta,',
    '            /** Compact lesson body + questionnaires for custom AI prompts. */',
    '            contextForAi: lessonContextBlockForAi,',
    '            /** Full branch playlist + questionnaire samples for dynamic narrative/quiz AI. */',
    '            branchContextForAi: curriculumContextBlockForAi,',
    '            /** Player + branch language profile (learnLang inferred from playlist). */',
    '            branchProfile: async function(anchorLesson, opts) {',
    '                var profile = Object.assign({',
    '                    playerName: user.username || \'Player\',',
    '                    playerLang: user.lang || \'EN\'',
    '                }, opts || {});',
    '                await curriculumContextBlockForAi(anchorLesson || null, profile);',
    '                return profile;',
    '            },',
    '            /** Command/output pairs extracted from lesson code fences. */',
    '            codeReplays: codeReplaysFromLesson,',
    '            /** Walk playlist until a lesson has practice tasks. */',
    '            findWithTasks: findLessonWithTasks',
    '        },',
    '        meta: {',
    '            read: readLessonMeta',
    '        },',
    '        /** Challenge Schema utilities for static mode games */',
    '        challenge: {',
    '            /** Check if a challenge object has all required fields */',
    '            isComplete: isChallengeComplete,',
    '            /** Get completeness score (0-5) and status */',
    '            getCompleteness: getChallengeCompleteness,',
            '            /** All lesson questionnaires on a lesson (challenge + challenges[]) */',
    '            fromLesson: getChallengesFromLesson,',
    '            /** Default empty challenge template */',
    '            template: function() {',
    '                return { core_concept: \'\', short_definition: \'\', main_question: \'\', correct_answer: \'\', traps: [], cloze_indices: [], steps: [], modes: [] };',
    '            },',
    '            /** Build duel/battle cards from lesson questionnaire (static-first). */',
    '            buildDuelDeck: function(lesson) {',
    '                return buildDuelDeckFromChallenge(lesson);',
    '            },',
    '            /** Practice tasks from Quiz V2 modes (+ optional code replays). */',
    '            tasksFromLesson: buildTasksFromLesson,',
    '            /**',
            '             * Lesson quiz modalities (multiple / recall / cloze / chips / steps).',
    '             * Mirrors arborito/src/features/learning/api/quiz-schema.js so cartridges and',
    '             * Python SDK (arborito_sdk) games can render the full Care/Study experience.',
    '             */',
    '            modes: {',
    '                ALL: ALL_QUIZ_MODES.slice(),',
    '                MULTIPLE: QUIZ_MODE_MULTIPLE,',
    '                RECALL: QUIZ_MODE_RECALL,',
    '                CLOZE: QUIZ_MODE_CLOZE,',
    '                CHIPS: QUIZ_MODE_CHIPS,',
    '                STEPS: QUIZ_MODE_STEPS,',
    '                isPlayable: function(challenge, mode) {',
    '                    return quizModeIsPlayable(challenge, mode);',
    '                },',
    '                playable: function(challenge) { return getPlayableModesImpl(challenge); },',
    '                challengeForPlay: function(challenge) {',
    '                    return quizModes && typeof quizModes.challengeForPlay === \'function\'',
    '                        ? quizModes.challengeForPlay(challenge)',
    '                        : challenge;',
    '                },',
    '                pick: function(challenge, blockId, salt) { return pickStudyQuizModeImpl(challenge, blockId, salt); },',
    '                buildCard: function(challenge, mode, opts) { return buildModeCardImpl(challenge, mode, opts); },',
    '                buildStudyCard: function(challenge, blockId, opts) { return buildStudyCardImpl(challenge, blockId, opts); },',
    '                /** Translated mode label, e.g. label(\'cloze\',\'ES\') -> \'Hueco\'. */',
    '                label: modeLabel,',
    '                /** CSS class fragment for styling per modality, e.g. " is-mode-cloze". */',
    '                className: modeClassName,',
    '                /** True when the player has to drag chips / steps into order (chips & steps modes). */',
    '                isOrdering: modeIsOrdering,',
    '                /** Compare what the player picked against the card\'s expected order. */',
    '                checkOrder: modeCheckOrder,',
    '                /** HTML for the answer area (chips for ordering, buttons for multiple-choice).',
    '                 *  opts: { showOpts, optsDisabled, lang }. */',
    '                renderAnswers: modeRenderAnswers',
    '            }',
    '        },',
    '        ask: {',
    '            json: function() {',
    '                if (aiMode === \'static\') {',
    '                    throw makeError(CODES.SAGE, \'AI not available in static mode. Switch to Dynamic AI mode to use ask.json.\');',
    '                }',
    '                return askJSONImpl.apply(null, arguments);',
    '            },',
    '            chat: function(messages, ctx) {',
    '                if (aiMode === \'static\') {',
    '                    throw makeError(CODES.SAGE, \'AI not available in static mode. Switch to Dynamic AI mode to use ask.chat.\');',
    '                }',
    '                return bridge.aiChat(messages, ctx);',
    '            },',
    '            /**',
    '             * Dynamic AI for games. lesson = current lesson; playerSaid = what the player typed.',
    '             * opts.authorLine = optional fixed text from the lesson (story/dialog); SDK adapts it to this branch.',
    '             * opts.persona = voice/character. opts.profile = optional { playerLang, learnLang }.',
    '             * Author questionnaires are always preferred; AI only fills gaps.',
    '             */',
    '            lessonAction: async function(lesson, playerSaid, opts) {',
    '                if (aiMode === \'static\') {',
    '                    throw makeError(CODES.SAGE, \'AI not available in static mode. Switch to Dynamic AI mode to use ask.lessonAction.\');',
    '                }',
    '                opts = opts || {};',
    '                if (!opts.persona && aiPersonaConfig.persona) opts.persona = aiPersonaConfig.persona;',
    '                var askOpts = Object.assign({}, opts.askOptions || {}, { lesson: lesson });',
    '                var prompt = await buildDynamicActionPrompt(lesson, playerSaid, opts);',
    '                return askJSONImpl(prompt, null, askOpts);',
    '            }',
    '        },',
    '        ai: {',
    '            get persona() { return aiPersonaConfig.persona; },',
    '            set persona(v) { aiPersonaConfig.persona = String(v || \'\'); },',
    '            get arborito() { return aiPersonaConfig.persona; },',
    '            set arborito(v) { aiPersonaConfig.persona = String(v || \'\'); }',
    '        },',
    '        narrative: {',
    '            start: playNarrative,',
    '            advance: playAdvanceNarrative',
    '        },',
    '        xp: function(n) { bridge.addXP(n); },',
    '        exit: function() { bridge.close(); },',
    '        save: function(k, v) { return bridge.save(k, v); },',
    '        load: function(k) { return bridge.load(k); },',
    '        memory: {',
    '            due: function() { return bridge.getDue(); },',
    '            getStatus: function(nodeId) {',
    '                return typeof bridge.getMemoryStatus === \'function\' ? bridge.getMemoryStatus(nodeId) : null;',
    '            },',
    '            isDue: function(nodeId) {',
    '                return typeof bridge.isMemoryDue === \'function\' ? bridge.isMemoryDue(nodeId) : false;',
    '            },',
    '            report: function(nodeId, quality) { return bridge.reportMemory(nodeId, quality); }',
    '        },',
    '        /** Platform helpers every cartridge gets for free.',
    '         *  Mobile-friendly tap, screen-size probing, and HTML-safe escaping. */',
    '        platform: {',
    '            /** Tap that doesn\'t fire twice on mobile. Returns a cleanup function. */',
    '            onTap: onTap,',
    '            /** { width, height } of the usable area (accounts for mobile chrome). */',
    '            getScreenSize: getScreenSize,',
    '            /** Subscribe to resize / orientation. Returns a cleanup function. */',
    '            onScreenChange: onScreenChange,',
    '            /** Escape text for safe HTML insertion. */',
    '            escapeHtml: escText,',
    '            /** Escape values for safe attributes. */',
    '            escapeAttr: escAttr',
    '        },',
    '        quiz: async function(lesson, opts) {',
    '            opts = opts || {};',
    '            var count = opts.count != null ? opts.count : 3;',
    '            var staticQuiz = staticQuizFromLesson(lesson, count);',
    '            if (aiMode === \'static\') {',
    '                if (!staticQuiz || !staticQuiz.length) {',
    '                    throw makeError(CODES.SAGE, \'Complete the lesson questionnaire to play in static mode.\');',
    '                }',
    '                return staticQuiz;',
    '            }',
            '            /* Dynamic: reuse author questionnaire when possible; AI fills remaining slots. */',
    '            if (staticQuiz && staticQuiz.length >= count) {',
    '                return shuffleArray(staticQuiz).slice(0, count);',
    '            }',
    '            var have = staticQuiz ? staticQuiz.length : 0;',
    '            var need = Math.max(1, count - have);',
    '            var prompt = await buildDynamicQuizPrompt(lesson, need, staticQuiz, opts.profile);',
    '            var aiItems = await askJSONImpl(prompt, null, opts.askOptions);',
    '            var merged = (staticQuiz || []).concat(Array.isArray(aiItems) ? aiItems : []);',
    '            if (!merged.length) {',
    '                throw makeError(CODES.EMPTY, \'AI_EMPTY_RESPONSE: Could not build quiz from lesson.\');',
    '            }',
    '            return merged.slice(0, count);',
    '        },',
    '        matchPairs: async function(lesson, opts) {',
    '            opts = opts || {};',
    '            var n = opts.count != null ? opts.count : 6;',
    '            var fillFromCurriculum = opts.fillFromCurriculum !== false;',
    '            var staticPairs = await staticMatchPairsWithCurriculumFill(lesson, n, fillFromCurriculum);',
    '            if (aiMode === \'static\') {',
    '                if (!staticPairs || staticPairs.length < 1) {',
    '                    throw makeError(CODES.SAGE, \'Complete the lesson questionnaire to play in static mode.\');',
    '                }',
    '                return staticPairs;',
    '            }',
            '            /* Dynamic: author questionnaire pairs first; AI fills remaining slots. */',
    '            if (staticPairs.length >= n) {',
    '                return staticPairs.slice(0, n);',
    '            }',
    '            var need = Math.max(1, n - staticPairs.length);',
    '            var prompt = await buildDynamicMemoryPrompt(lesson, need, staticPairs, opts.profile);',
    '            var aiPairs = await askJSONImpl(prompt, null, opts.askOptions);',
    '            var merged = sanitizeMemoryPairs(',
    '                (staticPairs || []).concat(Array.isArray(aiPairs) ? aiPairs : []),',
    '                n',
    '            );',
    '            if (fillFromCurriculum && merged.length < n && lesson) {',
    ' var curriculum = bridge.getCurriculum ? bridge.getCurriculum() : [];',
    '                var startIdx = -1;',
    ' for (var fi = 0; fi < curriculum.length; fi++) {',
    ' if (curriculum[fi] && curriculum[fi].id === lesson.id) {',
    '                        startIdx = fi;',
    '                        break;',
    '                    }',
    '                }',
    '                if (startIdx >= 0 && typeof bridge.getLessonAt === \'function\') {',
    ' for (var fj = startIdx + 1; fj < curriculum.length && merged.length < n; fj++) {',
    '                        var followL = await bridge.getLessonAt(fj);',
    '                        if (!followL || !lessonHasMemoryContent(followL)) continue;',
    '                        merged = sanitizeMemoryPairs(',
    '                            merged.concat(staticMatchPairsFromLessons([followL], n)),',
    '                            n',
    '                        );',
    '                    }',
    '                }',
    '            }',
    '            if (!merged.length) {',
    '                throw makeError(CODES.EMPTY, \'AI_EMPTY_RESPONSE: Could not build memory pairs from lesson.\');',
    '            }',
    '            return merged;',
    '        }',
    '    };',
    '    window.arborito.quiz.itemKey = quizItemKey;',
    '    window.arborito.quiz.buildOptions = buildQuizOptions;',
    '    window.arborito.quiz.pool = quizPoolFromCurriculum;',
    '    window.arborito.quiz.pick = pickUnusedQuiz;',
    '    window.arborito.quiz.answersMatch = answersMatch;',
    '    window.arborito.quiz.matchesAny = matchesAnyAnswer;',
    '    window.arborito.quiz.gradeAnswer = gradeQuizAnswer;',
    '    window.arborito.quiz.findCodeReplay = findCodeReplayMatch;',
]);
