#!/usr/bin/env node
/**
 * Copies all Noto Color Emoji woff2 subsets (11 unicode-range slices) into vendor/fonts/.
 * A single subset only covers flag emojis — Sage needs 🦉⚙️📝 etc. from other slices.
 * Run: npm install && npm run vendor:emoji
 */
import { copyFile, mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const fontsDir = join(root, 'vendor', 'fonts');
const OFL_DEST = join(fontsDir, 'OFL.txt');
const FACES_CSS = join(fontsDir, 'noto-color-emoji-faces.css');
const MANIFEST_JSON = join(fontsDir, 'noto-color-emoji-manifest.json');

const NOTO_PKG_CANDIDATES = [
  '@fontsource/noto-color-emoji',
  '@fontsource-variable/noto-color-emoji',
];

function findNotoPkgDir() {
  for (const pkg of NOTO_PKG_CANDIDATES) {
    const base = join(root, 'node_modules', pkg);
    if (existsSync(join(base, 'index.css'))) return base;
  }
  return null;
}

/** Parse @fontsource/noto-color-emoji/index.css into { file, unicodeRange }[] */
function parseNotoFaces(indexCss) {
  const faces = [];
  const blocks = indexCss.split('@font-face');
  for (const block of blocks) {
    const woff2 = block.match(/noto-color-emoji-(\d+)-400-normal\.woff2/);
    const range = block.match(/unicode-range:\s*([^;]+);/);
    if (!woff2 || !range) continue;
    faces.push({
      file: `noto-color-emoji-${woff2[1]}-400-normal.woff2`,
      unicodeRange: range[1].trim(),
    });
  }
  return faces;
}

async function main() {
  console.log('=== vendor:emoji (all Noto Color Emoji subsets) ===\n');
  const pkgDir = findNotoPkgDir();
  if (!pkgDir) {
    console.error('FAIL: @fontsource/noto-color-emoji not found. Run: npm install');
    process.exit(1);
  }

  const indexCss = await readFile(join(pkgDir, 'index.css'), 'utf8');
  const faces = parseNotoFaces(indexCss);
  if (!faces.length) {
    console.error('FAIL: could not parse Noto emoji @font-face blocks');
    process.exit(1);
  }

  await mkdir(fontsDir, { recursive: true });
  const srcFilesDir = join(pkgDir, 'files');
  let totalBytes = 0;

  for (const face of faces) {
    const src = join(srcFilesDir, face.file);
    const dest = join(fontsDir, face.file);
    if (!existsSync(src)) {
      console.error('FAIL: missing subset', src);
      process.exit(1);
    }
    await copyFile(src, dest);
    const { size } = await stat(dest);
    totalBytes += size;
    console.log('OK', face.file, `(${(size / 1e6).toFixed(2)} MB)`, face.unicodeRange.slice(0, 48) + '…');
  }

  const cssLines = faces.map(
    (f) =>
      `@font-face{font-family:"Arborito Emoji";font-style:normal;font-weight:400;font-display:swap;` +
      `unicode-range:${f.unicodeRange};` +
      `src:url("./${f.file}") format("woff2");}`
  );
  await writeFile(FACES_CSS, cssLines.join('\n') + '\n', 'utf8');
  await writeFile(MANIFEST_JSON, JSON.stringify(faces, null, 2) + '\n', 'utf8');
  const js = '// Auto-generated by scripts/vendor-emoji.mjs — do not edit.\nexport const NOTO_EMOJI_FACES = '
    + JSON.stringify(faces, null, 2) + ';\n';
  await writeFile(join(fontsDir, 'noto-emoji-manifest.js'), js, 'utf8');

  const licenseSrc = join(pkgDir, 'OFL.txt');
  if (existsSync(licenseSrc)) {
    // Upstream package ships the full OFL 1.1 text — prefer it verbatim.
    await copyFile(licenseSrc, OFL_DEST);
  } else if (!existsSync(OFL_DEST)) {
    // Last resort only when nothing exists yet: never overwrite a full
    // OFL.txt already vendored here (OFL 1.1 requires the complete text).
    await writeFile(
      OFL_DEST,
      'Noto Color Emoji — SIL Open Font License 1.1\nhttps://scripts.sil.org/OFL\n',
      'utf8'
    );
  }

  console.log(`\nOK ${faces.length} subsets → ${fontsDir} (${(totalBytes / 1e6).toFixed(1)} MB total)`);
  console.log('OK faces CSS →', FACES_CSS);
  console.log('OK manifest →', MANIFEST_JSON);

  const TTF_URL = 'https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf';
  const TTF_DEST = join(fontsDir, 'NotoColorEmoji.ttf');
  if (!existsSync(TTF_DEST)) {
    try {
      const res = await fetch(TTF_URL);
      if (res.ok) {
        const buf = Buffer.from(await res.arrayBuffer());
        await writeFile(TTF_DEST, buf);
        console.log('OK NotoColorEmoji.ttf →', TTF_DEST, `(${(buf.length / 1e6).toFixed(1)} MB)`);
      } else {
        console.warn('WARN: could not download NotoColorEmoji.ttf — HTTP', res.status);
      }
    } catch (e) {
      console.warn('WARN: NotoColorEmoji.ttf download failed:', e.message);
    }
  } else {
    console.log('OK NotoColorEmoji.ttf (cached)');
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
